-- 创建业务库（OLTP：在线交易库）
CREATE DATABASE IF NOT EXISTS demo_oltp;
USE demo_oltp;

-- 用户表（u_user）
CREATE TABLE IF NOT EXISTS u_user (
  user_id INT PRIMARY KEY AUTO_INCREMENT COMMENT '用户ID（自增主键）',
  username VARCHAR(50) NOT NULL COMMENT '用户名',
  register_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间（新增标识）',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间（增量标识）'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 商品表（p_product）
CREATE TABLE IF NOT EXISTS p_product (
  product_id INT PRIMARY KEY AUTO_INCREMENT COMMENT '商品ID（自增主键）',
  product_name VARCHAR(100) NOT NULL COMMENT '商品名称',
  price DECIMAL(10,2) NOT NULL COMMENT '商品价格',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间（新增标识）',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间（增量标识）'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 订单表（o_order）
CREATE TABLE IF NOT EXISTS o_order (
  order_id INT PRIMARY KEY AUTO_INCREMENT COMMENT '订单ID（自增主键）',
  user_id INT NOT NULL COMMENT '关联用户ID',
  total_amount DECIMAL(10,2) NOT NULL COMMENT '订单总金额',
  order_status TINYINT NOT NULL COMMENT '订单状态（1-待支付，2-已支付，3-取消）',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间（新增标识）',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间（增量标识）',
  FOREIGN KEY (user_id) REFERENCES u_user(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 订单明细表（o_order_detail）
CREATE TABLE IF NOT EXISTS o_order_detail (
  detail_id INT PRIMARY KEY AUTO_INCREMENT COMMENT '明细ID（自增主键）',
  order_id INT NOT NULL COMMENT '关联订单ID',
  product_id INT NOT NULL COMMENT '关联商品ID',
  quantity INT NOT NULL COMMENT '购买数量',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间（新增标识）',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间（增量标识）',
  FOREIGN KEY (order_id) REFERENCES o_order(order_id),
  FOREIGN KEY (product_id) REFERENCES p_product(product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
